---
title: "Notes/Remarques"
author: "Manon Eluard"
date: "2024-04-03"
output: 
  html_document:
    css: styles.css
---

### I. Article : "The Global distribution of Authorship in Economics Journals" - Notes

1.  **General idea**

    \
    Global distribution of authorship in economic journals by country/region, by quality of journal, and by **several** fields of specialization\

2.  **Points of methodology**

-   Data : Web of Science

-   Weights for cases where there are multiple authors for an article/and or multiple institutional affiliations

-   Measure of the regions : three possible regions for an author's affiliation = USA ; non-USA advanced economy ; developing economy. Authors are allocated to countries based on the *location of their institutional affiliations*.
<span class ="comment"> I wonder if they say something about an author having multiple affiliation. I guess they take all of the affiliations (or do they take the first one?).</span>

-   Measures of the citations (two alternatives) : citations per year since publication / citations in the first five years following publication
<span class ="comment">We can measure the former (we have the total citations and the year of publication, so we can measure the number of citations per year. But I wonder how they measure the latter. Do they say something: if they have the variable as such in their data? Maybe it's actually a variable in the Web of Science data that we have as well in the dictionnary.</span>

3.  **Results**

    **3.1. Geographical concentration analysis :**

-   Comparison between low-income and high-income countries based on the **location of the authors**

-   Share of all publications by author regional affiliation(s) : mainly USA and non-USA advanced countries

-   Distribution of frontier economics research vs global economic activity in **top-10 journals**

<span class ="comment">I'm just curious to know how they've measured their top-10 journals, and their top-100</span>

    -   Regional distribution of authorship in top 10 journals: distribution highly skewed towards the rich regions of the world. This degree of concentration is difficult to explain by economic resources (distribution of the GDP across countries). Imbalance particularly striking for East and South Asia.

        -   Evolution of regional shares in GDP/frontier economic research over time:

            -   USA top 1 since a long time

            -   Gains made by other advanced economies (non-USA advanced).

            -   The problem of under-representation of developing countries in top research publications has been getting worse over time

    -   Trends in geographical concentration according to **different categories of journal quality** :

        -   The lower the quality raking of a journal, the higher non-USA representation

        -   Non-USA advanced economies have generally made progress across all journal categories

        -   Progress also for developing countries but mainly in the top 100 journal, of lower quality and least prestigious)

        -   Differences across developing countries. Ex : increasing representation for East Asia especially China, due to the economic rise of the region, and a drop for MENA regions.

<span class ="comment">I wonder if tey document a bit more the Chinese rise. How does it compare in terms of percentage increase to other countries? In any case, that's something we could document better in out project.</span>

        **3.2.** Trends across different **journals by fields**

-   Increase of *non-USA advanced country* authors in many fields (development, econometrics...) and *decline for USA authors*.

-   Analysis for top 100 journals :

    -   In several fields (finance, micro...) USA authors continue to have the largest share.

    -   For developing countries : no fields where they seem to have made significant gains.

        Rq: stated result contradicts the figures given in the table (table 4) where we see an increase in the share (in percentage points) of developing countries in journals in almost every field, so I don't understand.
        
        <span class ="comment">You're right, I think their interpreations don't go enough in the details. It seems that US is losing share wrt non-USA advanced, and wrt to Developing (especially China)</span>

        **3.3. Citation** analysis :

-   Graphics: Top 10 most cited publication in data set by authors / average number of citations per year by fields

-   Citation trends by region : proportion and evolution of authors cited from a certain nationality.\
    Main result : articles written by the USA authors receive about 50% more citations

-   Comparison of the proportion of articles cited in a region and the proportion of total articles in the region

4.  **Econometric/regression analysis and results :** proportion of articles published in **top journals by regions.**

USA-affiliated authors receive more citations and a higher share of these are published in top 10 journals. This can be due to selection effect e.g. authors in advanced economies publish higher quality articles so they have more citations.\
\
This is why the authors estimate the probability of being published in a top 10 journal (dependent variable) by using : the location as an explanatory variable of interest, a **proxy control for article quality = citations** per year and fixed effects by year.

Second step : Use of an instrumental variable (?) = citations : explained by the location (explanatory variable) journal field, journal rank group and fixed effects by year.

<span class ="comment">I'm not sure I get why there is endogeneity here and how do they treat this?</span>

Results :

-   Articles by authors located outside the USA have a lower probability of being published in a top 10 journal, even for controle for article quality (citations).

-   Developing country authorship negatively associated with the likelihood for an article being published in top journal

-   Analysis of this evolution over time : increase in energy/environment/agriculture journals for developing countries vs no increase in development and international (surprisingly).

<span class ="comment">OK, so I guess, their regression analysis does not add much value tot their descriptive analysis of the data, as it gives the same statistical associations between place of origins and qualiy of publications.</span>

### II. Article : "Inside Job or Deep Impact? Extramural Citations and the Influence of Economic Scholarship" - Notes

1.  General idea\
    \
    The goal of this article, which is about the economics' interactions with other disciplines, is to assess the influence of economic scholarship through extramural citations i.e the frequency with which other disciplines cite papers in economic journals.

    **Citations = measure of influence**\
    
    <span class ="comment">Do they look only at whether other disciplines use economics' research articles, or also the other way around (how economics uses other disciplines' research?)</span>

2.  Points of methodology :

-   Data : Web of Science / EconLit database because it included Journal of Economic Literature codes, used to classify papers into economics fields.
<span class ="comment">We don't have yet all EconLit Journal of Economic Literature codes, but only for climate change related articles</span>

-   Documenting levels and trends in overall influence by disciplines.\
    To do so, they need to define disciplines : non economics disciplines such as sociology or psychology and non-social-science discipline such as mathematics or medicine.\
    Each journal corresponds to **one** discipline.
    
<span class ="comment">I think here, we need a bit more details on how they define these disciplines, and how do they put a journal in one discipline.</span>    

-   Explore types of economic research that seem responsible for increasing extramural influence.

    -   Machine learning to differentiate : fields (e.g macro or industrial organization) and "styles" theoretical/econometric/empirical papers.

    -   The authors also capture the evolution of the "styles" in economics (rise of empirical work for instance, due to the increased use of randomized trials and quasi-experimental research designs).

-   Computation of the share of citations from discipline to a group of disciplines. Ex : the citation share from economics to the group of business disciplines is the sum of shares of economics cites to finance, marketing, management and accounting.

<span class ="comment">Just to be sure, as it is the share, they compute the share at the article level (like if an articles  has 50 citations, whose 10 are in the business disciplines, which would mean that 20% of the citations share in this economic article are in reference to business disciplines? Or is it at another level (like the journal level?). </span>

-   Weighting scheme for the citations : weights emphasize journals that are important for the discipline studied.

<span class ="comment">Maybe we need some details on the way they weight journals.</span>

3.  Results :

-   Rise in the influence of economic research, especially growth in citations to **empirical work**.

    Especially, empirical economics is a cause of the increase in the extramural influence of economics : more accessible and reliable thanks to the use of data instead of theoretical hypothesis.

-   Economics is increasingly likely to reference other social sciences

### III. Ideas

1.  Idées - Analyse **géographique** :

-   Analyser la représentation des articles publiés dans les meilleures revues non pas en étudiant la localisation des auteurs, mais en se concentrant sur leur **nationalité** (ce qui peut nous permettre d'aller plus loin que ce qui existe déjà dans la littérature).\
    Peut-être que ce n'est pas possible au vu des données (pas d'information sur l'origine nationale des auteurs, il me semble, et cela peut être assez compliqué à construire).
    
    <span class ="comment">En effet, cela peut être intéressant de croiser affiliationn ET nationalité. D'autant plus que l'on peut imaginer que bcp d'auteurs affiliés dans des pays développés ne sont pas de la nationalité de ces pays. On peut imaginer que leurs recherches peuvent servir d'autres intérêts. On pourra imaginer plus tard un algorithme nous permettant d'obtenir la nationalité des auteurs (j'ai quelques idées).</span>

    2.  Idées - Analyse des **citations** :

-   Analyser le "**home-country effect**", à l'image de l'article "The Global Distribution of Authorship in Economic Journals", c'est à dire le fait que les auteurs sont davantage susceptibles de citer des articles provenant de leurs pays "domestiques".

<span class ="comment">Si l'on envisage une analyse économétrique des citations en économie du changement climatique, cela peut être un point important. Possible qu'au sujet du changement climatique, en tant que problème de pollution global avec des problématiques locales, le home country effect ait un rôle ambigu. </span>

-   Quantifier les citations d'articles en économie vers d'autres articles qui se concentrent sur l'économie du climat et inversement. Le faire pour chaque discipline envers l'économie du climat et l'économie du climat envers chaque discipline.

<span class ="comment">C'est toute l'idée du projet. D'autant plus que c'est un champ de l'économie qui se voudrait plus multidisciplinaire/transdisciplinaire que les autres. Nous aurions donc cet article comme point de comparaison du degré d'ouverture aux autres disciplines des différents champs de l'économie. On pourrait alors regarder en quoi le chanmp de l'économie du changement climatique s'écarte/se rapproche de cela. </span>

    3.  Idées - Analyse **économétrique** : essayer d'établir certaines corrélations voire des causalités une fois que l'on a réalisé ces premières analyses

<!-- -->

-   Ajouter d'autres variables issues d'autres bases de données (ex: World Bank - GDP) pour essayer d'expliquer certaines observations, à l'image de l'article "The Global Distribution of Authorship in Economic Journals" qui compare la part du pays dans le GDP vs la part du pays dans la recherche économique.

    -   Ex pour le genre : comparer les différences de parités dans les auteurs entre les pays selon différents niveaux d'éducation (est-ce que ce manque de parité dans ce pays est dû à un niveau d'éducation plus faible chez les femmes/ou d'autres facteurs auxquels on pourrait réfléchir).
    
<span class ="comment">Dans le cas de la parité, on peut tout à fait envisager de croiser genre et niveau d'éducation (tableau croisé). Mais à mon avis, on risque surtout de capturer l'idée que les parcours d'étude sont systématiquement genrés, et donc d'avoir assez peu de différences entre pays (avec peut-être quelques exceptions). Cela vaudra toujours le coup d'étudier la question, avec aussi l'idée de comparer la question de la représentation de genre dans le cas de l'analyse économique du changmeent climatique, vis-à-vis du reste de l'économie, voir des autres disciplines. Est-ce qu'il y a relativement plus de femmes qui font partie des auteurs d'articles portant sur le changement climatique? Qu'est-ce que cela peut vouloir dire en termes de travaux de recherche (ici, nous pourrons lire des travaux sur les différences de traitement genrés dans la recherche en général, et en économie.) </span>

    -   Ex pour les citations : étudier les barrières d'accès (asymétrie d'informations) ou les exclusions dues à des réseaux qui sont fermés

        4.  Questions qui me sont venu en lisant :

<!-- -->

-   Quel est le but derrière des analyses de genre et des analyses de concentration géographique ?

    -   Pour le genre : Est-ce pour constater des inégalités de genre au sein de la recherche économique sur l'économie du climat, et si oui essayer de l'expliquer économétriquement pour établir des liens de causalité ?
    
    <span class ="comment">Je pense que je réponds en partie à ta question avec mon commentaire précédent. Il y a en effet une question de constattation/quantification. Mais il faudrit que l'on réfléchisse également à ce que cela voudrait dire pour cette recherche, le fait qu'elle soit très souvent mené par des hommes (en termes d'inclusivité des travux, d'études des impacts, cela entraîne nécessairement des biais que laa grande majorité de la recherche soit menés par des hommes). A ce sujet, il y a des travaux (menés par des femmes) qui montrent les inégalités de genre face au changement climatique. On pourra s'intéresser à ces questionns en parallèle que l'on quantifiera la place du genre dans la recherche en économie du changement climatique.</span>

    -   Pour les régions : Est-ce que le but est de constater les inégalités entre les pays au niveau de l'avancement dans le domaine de la recherche économique et si oui essayer de l'expliquer économétriquement pour établir des liens de causalité ? Ou bien est-ce seulement pour faire un état des lieux des pays qui sont étudiés dans le domaine de l'économie du climat ? Cela peut être intéressant de faire les deux.
    
   <span class ="comment">Ici, le projet est bien de faire les deux. Quantifier la distribution géographique, et documenter des possibles inégalités (et aussi comparer le cas du changement climatique par rapport au reste de l'économie). Dans le cas du changement climatique, on pourrait faire une analyse assez proche de celle du premier article, où l'on compare la part des contributions des chercheurs selon leur origine (non pas à la part de leur pays dans l'économie mondiale) mais à la part de leur pays dans le changement climatique (soit en emissions de CO2 cumulés, soit également en efforts de réduction, ou bien encore en termes d'impacts à venir du changement climatique).</span>

-   Si j'ai bien compris lors de notre discussion, un des points intéressants dans ce travail de recherche est notamment d'étudier la répartition géographique/le genre des auteurs dans un domaine spécifique : l'économie du climat.

    Dans la mesure où ce travail a déjà été fait pour d'autres domaines, l'objectif final est-il de faire le même travail mais sur un sujet différent, à savoir l'économie du climat, ou de se concentrer sur plusieurs domaines de spécialisation en économie et d'ajouter des spécifications à l'étude de la répartition des auteurs (cf. par exemple étudier la dispersion géographique non seulement en étudiant la localisation des auteurs, mais aussi en étudiant la nationalité des auteurs).
    
    <span class ="comment">C'est bien ça l'idée! On se sert de ces travaux un peu plus généraux, pour appliquer ces questions au cas du traitement du changement climatique par les économistes. L'idée est bien de quantifier l'effort de recherche réalisés par les chercheurs dans ce champ, afin d'en faire un état des lieux et d'essayer de mesurer/identifier des enjeux d'inégalité / ou d'amélioration possible dans la manière d'effectuer la recherche.</span>
