---
title: "Notes/Remarques"
author: "Manon Eluard"
date: "2024-04-03"
output: html_document
---

### Article : "The Global distribution of Authorship in Economics Journals" - Notes

-   Distribution by country/region (three possible regions for an author's affiliation = USA ; non-USA advanced economy ; developing evonomy, by quality of journal, and by **several** fields of specialization

```{=html}
<!-- -->
```
-   **Geographical concentration** analysis : Comparison between low-income and high-income countries based on the **location of the authors** (authors are allocated to countries based on the *location of their institutional affiliations*)
    -   Share of all publications by author regional affiliation(s) : mainly USA and non-USA advanced countries

    -   Distribution of frontier economics research invs global economic activity : **top-10 journals**

        Regional distribution of of authorship in publications in **top-10 journals** : distribution highly skewed towards the rich regions of the world. This degree of concentration is difficult to explain by economic resources (distribution of the GDP across countries). Imbalance particulary striking for East and South Asia.

        Evolution of regional shares in GDP and frontier economic research over time (**top-10 journals)** : USA top 1 since a long time / gains made by other advanced economies (non-USA advanced) / the pb of under-representation of developing countries in top research publications has been getting over time

    -   Trends in geographical concentration according to different categories of journal quality : the lower the quality raking of a journal, the higher non-USA representation / non-USA advanced economies have generally made progress across all journal categories / progress also for developing countries but mainly in the top 100 (lower quality, least prestigious) and differences across developing countries (ex : increasing representation for East Asia especially China, due to the economic rise of the region, and a drop for MENA regions)
-   Journals by field : trends across different fields
    -   increase of non-USA advanced country authors in many fields (development, econometrics...) and decline for USA authors

    -   analysis for top 100 journals : in several fields (finance, micro...) USA authors continue to have the largest share. For developing countries : no fields where they seem to have made significant gains
-   **Citation** analysis :
    -   proportion and evolution of authors cited from a certain nationality. Main result : articles written by the USA authors receive about 50% more citations

    -   Top 10 most cited publication in data set by authors / average number of citations per year by fields
-   Points of methodology :
    -   Weights for cases where there are multiple authors for an article/and or multiple institutional affiliations

    -   Measures of the citations (two alternatives) : citations per year since publication and citations in the first five years following publication
-   **Econometric analysis**/regressions :
    -   proportion of articles from developing countries published in **top journals**

    -   analysis of this evolution over time : increase in energy/environment/agriculture journals vs no increase in development and international

    -   correlation analysis : developing country authorship negatively associated with the likelihood for an article being published in top journal

Ideas :

-   analyzing the representation of articles published in top journals not by studying the location of the authors but by focusing on their **nationality** (goes one step further). Maybe it's not possible regarding the data (no information on the national origin of the authors?)

-   Citation : analysis of the home-country effect = to cite domestic articles.

-   Pour les analyses économétriques, idée : ajouter d'autres variables issues d'autres bases de données (ex: WB - GDP) pour essayer d'expliquer certaines observations. Ex issu de l'article : part du pays dans le GDP vs part du pays dans la recherche économique. Ex de variables : variables concernant la parité homme femme au sein d'un pays/le niveau d'éducation, les comparer avec la représentativité par pays, selon le genre, dans la recherche économique. Mais est-ce que cela pourrait être pertinent ? En tout cas intéressant ++ si on peut essayer d'au moins établir des corrélations...

Contribution of our work : if I understood well from our discussion, what is interesting in this research work is to assess the geographical distribution of economics research authorship but on a specific field **= climate economics**, insofar as this work has already been done for other fields. Le but final est-il de faire le même travail mais sur un sujet différent i.e l'économie du climat, ou bien de se focaliser sur plusieurs domaines de spécialisation en économie et d'ajouter des spécifications à l'étude de la distribution des auteurs (cf supra étudier la dispersion géographique pas seulement en étudiant la localisation des auteurs, mais leur nationalité). En fait quel est le but derrière ce que l'on fait ? Pourquoi on regarde les différences de genre entre les auteurs dans la littérature économique ? Est-ce pour constater des inégalités de genre au sein de la recherche économique, et si oui essayer de l'expliquer ? Même question pour les pays. Est-ce que le but c'est de constater les inégalités entre les pays au niveau de l'avancement dans le domaine de la recherche économique et si oui, cela peut effectivement être intéressant de l'expliquer économétriquement) ou bien est-ce seulement pour faire un état des lieux des sujets/pays étudiés dans le domaine de l'économie du climat ? Cela peut être intéressant de faire les deux.

Nom variables Corpus.Short

-   TI : nom de l'article
-   AU : nom de(s) auteur(s) - séparation des auteurs par un point virgule (à priori) et séparation des noms et prénoms par une virgule (nom en première position et prénom en second)
-   

questions : le truc des tables, ca va être super lourd si on fait ça pour chaque article
