<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-02-06">

<title>Quantifying interactions between economics of climate change, the rest of economics and other disciplines</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="QuantifCCEcon_files/libs/clipboard/clipboard.min.js"></script>
<script src="QuantifCCEcon_files/libs/quarto-html/quarto.js"></script>
<script src="QuantifCCEcon_files/libs/quarto-html/popper.min.js"></script>
<script src="QuantifCCEcon_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QuantifCCEcon_files/libs/quarto-html/anchor.min.js"></script>
<link href="QuantifCCEcon_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QuantifCCEcon_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QuantifCCEcon_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QuantifCCEcon_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QuantifCCEcon_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Quantifying interactions between economics of climate change, the rest of economics and other disciplines</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 6, 2025</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Gender disparities in scientific research remain a pressing issue, with significant impacts on the balanced development of the field. In particular, gender role positioning and educational restrictions continue to hinder equitable progress in scientific research. This study aims to provide a quantitative analysis of these gender disparities <em>within the specific context of climate economics</em>, considering various levels of journal prestige and types of collaborations.</p>
<p>Previous research has delved into the broader issue of gender disparities in economics. For instance, David Card, Stefano Della Vigna, Patricia Funk, and Nagore Iriberri (2019), in their paper “Are Referees and Editors in Economics Gender Neutral?”, examined the role of gender in the evaluation of economic research. They highlighted that editorial process is not gender-neutral when considering differences in paper quality and field: female-authored papers get more citations than male-authored papers. It shows that female researchers have characteristics that lead to higher citations, especially differences in empirical content but are held to a higher standard, perhaps because of stereotype biases.</p>
<p>Similarly, Junwan Liu, Yinglu Song, and Sai Yang (2019), in their paper “Gender Disparities in the Field of Economics,” analyzed gender disparities in terms of research output and influence across different countries, institutions, and journal levels. Their findings indicate a dominance of male authors in terms of research output and influence, with significant geographical variations. Their study also revealed that the output of both male and female authors decreases logarithmically with career age, while the influence of female authors tends to increase with longer careers due to higher qualifications.</p>
<p>Building on these foundational studies, our research utilizes a larger and more diverse data set, drawing from the Web of Science database and Scopus, which includes information on over 600,000 articles. Our analysis focuses on climate economics, aiming to uncover gender disparities by examining differences across journal levels and collaboration types. Specifically, we categorize journals into top five and top thirty tiers and analyze the degree of mixed-gender collaborations within these articles. Our objective is to validate and extend previous findings within the niche of climate economics, thereby contributing to the understanding of gender inequalities in this crucial area of research.</p>
</section>
<section id="data-cleaning-and-gender-assignment-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning-and-gender-assignment-algorithm">Data cleaning and gender assignment algorithm</h2>
<p>To accurately assess gender disparities in scientific research, a rigorous data cleaning and gender assignment process is essential. This section outlines the methodology employed to clean the data set and assign gender probabilities to authors’ first names.</p>
<section id="data-cleaning-process" class="level4">
<h4 class="anchored" data-anchor-id="data-cleaning-process">Data Cleaning Process</h4>
<p>Initially, we considered a sample of 60,000 observations, focusing on articles with 15 authors or fewer, which constitute 99.95% of the data set. For each article, we extracted in our initial data base all authors’ full names, names and first names. The cleaning process aimed to ensure compatibility with the “gender” package in R and involved several steps. We applied this cleaning for full names, first and last names. We first removed text in brackets, extraneous spaces, in particular those at the beginning and end of names and any letters followed by a period. In handling compound names, we retained only the first name. Finally, we replaced all accents with their unaccented equivalents. These steps ensured that the first names were in a suitable format for gender identification.</p>
</section>
<section id="gender-assignment-algorithm" class="level4">
<h4 class="anchored" data-anchor-id="gender-assignment-algorithm">Gender Assignment Algorithm</h4>
<p>After cleaning the data, we utilized the “gender” package in R to associate a gender and gender probabilities to any first name. To do so, we first create functions that compute gender probability for a given first name employing two methods: the “ssa” method, which uses data from the US Census List, and the “napp” method, which reallocates gender probabilities for names not identified by the “ssa” method. This dual-method approach resulted in a comprehensive data frame combining the results from both methods and giving, for each unique first name, the probability for the name to be female and male. This data frame finally gives all first names that for which we have an assigned gender probability.</p>
<p>We then developed an algorithm to assign a gender to each author’s first name, using four main databases: the final data frame from the previous gender probability assignment, a list of common Chinese first names, and lists of the top 10 male and female economists. This algorithm allows to create three new variables : a variable which attributes a gender to each first name and variables that give the probability for the first name to be male or female.</p>
<p>For the gender variable, the algorithm uses several conditional steps. This variable can take value NA, unknown, male or female. We first focus on the full name for each author in the algorithm to define the variable gender. If the full name is missing in our initial data base, the gender variable is set to NA. Otherwise, if the full name is in the list of top 10% of female economists, gender is set to female. Reciprocally, if full name is in the list of top 10% of male economists, gender is set to male. Then, we treat first name for each author in the algorithm to define the variable gender. If first name is missing in our initial data base, gender variable is set to NA. If first name is in the list of common chinese first name, gender is set to “unknown”. If first name is absent from the list of first names with measured gender probability (absent from the data frame that we created during the prevous step), gender is set to “unknown”. For recognized first names, if the probability of being male in this list was greater than 90%, the name was assigned “male”; if less than 10%, it was assigned “female”; if between 10% and 90%, the gender was marked as “undecided”.</p>
<p>Additionally, the algorithm created variables indicating the probability of each first name being male or female, only if gender is assigned. These variables are varying between 0 and 1 or take value NA. As for the gender variable, the algorithm first treat full names for each author and then first names. If the full name is missing from our initial data base, both probabilities are set to NA. If the full name is is the list of top 10% of female economists, the probability for the first name to be female is set to 1 and 0 for male. Reciprocally, if the full name is in the list of top 10% of male economists, the probability for the first name to be female is set to 0 and 1 for male. Then, we treat first name for each author in the algorithm to define probabilities gender. If a first name is missing from our initial data base, both probabilities were set to NA. If a first name appeared on the list of common Chinese names, both probabilities were also set to NA. If first name is absent from the list of first names with measured gender probability (absent from the data frame that we created during the previous step), both probabilities were set to NA. If the first name was found and recognized as “male” or “female,” the respective probabilities were assigned accordingly from the data frame assigning gender probabilities.</p>
<p>This comprehensive algorithm ensures a robust assignment of gender probabilities to each author’s first name, facilitating a detailed analysis of gender disparities in the field of climate economics.</p>
</section>
<section id="creation-of-variables-of-interest-proportion-of-male-and-female-authors-and-gender-type-of-co-authorship" class="level4">
<h4 class="anchored" data-anchor-id="creation-of-variables-of-interest-proportion-of-male-and-female-authors-and-gender-type-of-co-authorship">Creation of variables of interest: proportion of male and female authors and gender type of co-authorship</h4>
<p>Thanks to this algorithm, we are able to calculate the proportion of authors who have been assigned to a male gender among all authors, as well as the proportion of authors who have been assigned to a male gender among authors whose gender has been correctly assigned. We are able to make the same type of calculation for the proportion of authors who have been assigned a female gender.</p>
<p>Finally, we generate five variables for gender type of co-authorship. These variables are defined as “F” if there is only one author in the article and if this author has a female gender, “M” if there is only one author and if this author has a male gender, “MM” if there is more than 1 author and if these authors are only male, “FF” if there is more than 1 author and if these authors are only female, and finally “MF” if there is more than 1 author and if these authors are both male and female. These variables will be useful for the computation of descriptive statistics and further data analysis.</p>
</section>
</section>
<section id="quality-and-limits-of-the-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="quality-and-limits-of-the-algorithm">Quality and limits of the algorithm</h2>
<p>Having cleaned up the data and created our algorithm for assigning a gender to each existing first name, we now check the quality of our algorithm.</p>
<section id="comparison-between-total-number-of-first-names-and-first-names-with-assigned-gender-before-the-use-of-an-assignation-gender-algorithm" class="level4">
<h4 class="anchored" data-anchor-id="comparison-between-total-number-of-first-names-and-first-names-with-assigned-gender-before-the-use-of-an-assignation-gender-algorithm">Comparison between total number of first names and first names with assigned gender before the use of an assignation gender algorithm</h4>
<p>First and before constructing our algorithm, we can compare the total number of unique first names in our database with the total number of first names that can be correctly assigned to a gender. The latter is calculated using the data frame, which uses the “ssa” and “napp” methods to assign a gender to the first name.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 95589</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>We have 95,589 unique first names in our database. The total number of first names that can be assigned to a gender thanks to the “ssa” and “napp” method is 24 142. We therefore had roughly 75% of first names whose gender which could not be determined only using the SSA and NAPP methods, and which will not be recognized by these methods.</p>
<p>Indeed, unmatched first names appear to come from non-Western cultures. These first names are fairly rare and do not recur regularly in the articles, so they have little effect on matching. However, this is an important limitation in that we are not able to assign a gender probability to non-Western first names, insofar as those first names will be defined as “unknown” while using the list of common Chinese names in our algorithm. This limit omits a whole part of the analysis for non-Western first names and therefore introduces a significant selection bias. However, the construction of the algorithm as we did and especially the use of lists for top 10 male and female economists will help us to identify correctly a large part of those unidentified gender.</p>
</section>
<section id="analysis-of-gender-assignment-at-author-level" class="level4">
<h4 class="anchored" data-anchor-id="analysis-of-gender-assignment-at-author-level">Analysis of gender assignment at author level</h4>
<section id="checking-the-algorithm-by-number-of-authors-per-article" class="level5">
<h5 class="anchored" data-anchor-id="checking-the-algorithm-by-number-of-authors-per-article">Checking the algorithm by number of authors per article</h5>
<p>To construct an analysis of the gender assignment at author level, we first looked at how well the algorithm is able to assign a genre to authors per article.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 4
   nb_authors mean_ratio med_ratio nb_article
        &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;int&gt;
 1          1      0.561     1         456915
 2          2      0.617     0.5       347291
 3          3      0.648     0.667     199915
 4          4      0.622     0.75       76416
 5          5      0.598     0.6        28348
 6          6      0.558     0.667      12647
 7          7      0.554     0.571       6054
 8          8      0.546     0.625       3367
 9          9      0.554     0.667       2002
10         10      0.551     0.6         1242
11         11      0.567     0.636        742
12         12      0.618     0.75         510
13         13      0.621     0.769        301
14         14      0.622     0.786        161
15         15      0.652     0.8          144</code></pre>
</div>
</div>
<p>The results show descriptive statistics for the ratio of authors with an identified gender among the total number of authors for articles, grouped by number of authors. The results show that the average proportion of authors with an identified gender inreases slightly as the number of authors per article increases For example, articles with a single author have an average of 0.5611 authors with identified gender among the total number of authors, while those with fifteen authors have a higher average of 0.651. Regarding the median of the ratios, it decreases with the number of authors per article. For instance, articles with one author have a median of 1.0000, indicating that all authors have an identified genre, while this median proportion decreases as the number of authors increases to reach 0.8 for articles with fifteen authors. Overall, these trends suggest that in articles with a greater number of authors, it is less likely that all authors have an identified gender, which could be due to greater diversity or less complete author information.</p>
<p>Commentaire: interprétation générale = baisse de la médiane mais la moyenne augmente donc donne des résultats différents - pas sûre de l’interprétation finale et de ce que l’on doit privilégier en termes d’analyse (la moyenne ou la médiane).&nbsp;</p>
</section>
<section id="checking-the-algorithm-by-number-of-articles-per-author" class="level5">
<h5 class="anchored" data-anchor-id="checking-the-algorithm-by-number-of-articles-per-author">Checking the algorithm by number of articles per author</h5>
<p>To improve the analysis of the quality of the author-level gender assignment algorithm, we enhance our analysis by checking the algorithm against the number of articles per author.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 FALSE   TRUE 
774315  52904 </code></pre>
</div>
</div>
<p>The table shows statistics on the gender assignment of authors based on the number of articles they have written. Out of a total of 827,219 authors, around 93.6% (774,315) have had their gender correctly assigned after the use of the gender assignation algorithm, while around 6.4% (52,904) have missing genders, regardless of the number of articles they have written and independantly of the type of assignation which can be “female”, “male”, “undecided” or “unknown”.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   female      male undecided   unknown      &lt;NA&gt; 
   172987    297279     36540    267509     52904 </code></pre>
</div>
</div>
<p>Of these, 20.9% (172,987) authors are identified as women, 35.9% (297,279) as men, (4.4% ) 36,540 have an undetermined gender, and 32.3% (267,509) have an unknown gender.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 45,672 × 8
   firstname  lastname  fullname          fulln…¹ gender propo…² propo…³ n_art…⁴
   &lt;chr&gt;      &lt;chr&gt;     &lt;chr&gt;             &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;
 1 Asmak      Ab Rahman Asmak Ab Rahman   " Ab R… unkno…  NA     NA           18
 2 Qaiser     Abbas     Qaiser Abbas      " Abba… unkno…  NA     NA           11
 3 Babak      Abbasi    Babak Abbasi      " Abba… male     1      0           12
 4 Mohd       Abd Karim Mohd Zaini Abd K… " Abd … male     1      0           17
 5 Tahirou    Abdoulaye Tahirou Abdoulaye " Abdo… unkno…  NA     NA           24
 6 Ghulam     Abid      Ghulam Abid       " Abid… male     1      0           14
 7 Ibrahim    Abouleish Ibrahim Abouleish " Abou… male     1      0           22
 8 Keith      Abrams    Keith R. Abrams   " Abra… male     0.995  0.0052      15
 9 Abdulfatai Adedeji   Abdulfatai A. Ad… " Aded… unkno…  NA     NA           12
10 Sveinn     Agnarsson Sveinn Agnarsson  " Agna… male     1      0           11
# … with 45,662 more rows, and abbreviated variable names ¹​fullname2,
#   ²​proportion_male, ³​proportion_female, ⁴​n_articles</code></pre>
</div>
</div>
<p>A significant proportion of authors therefore have an undecided or unknown gender, due to the large proportion of non-Western first names that we did not manage to assign. In particular, the majority of authors with more than 10 articles are East Asian names, which may explain these figures and difficulties in correctly assigning gender due to the diversity of names and gender conventions in this region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># By number of articles written for each author, how much missing gender?</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(authors_df<span class="sc">$</span>n_articles, authors_df<span class="sc">$</span>gender, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        female   male undecided unknown   &lt;NA&gt;
  1     111890 167346     21058  165074  36326
  2      25829  44072      5446   40601   7707
  3      11475  21391      2651   18690   3174
  4       6305  12929      1579   10630   1622
  5       3904   8765      1058    6982   1006
  6       2739   6359       746    4904    669
  7       2002   5087       615    3797    448
  8       1515   4010       441    2863    349
  9       1224   3357       374    2284    254
  10       967   2822       361    1825    206
  11       771   2332       293    1426    140
  12       652   1999       230    1192    108
  13       525   1717       182     996     91
  14       444   1455       155     790    110
  15       362   1345       124     701     74
  16       291   1164       103     592     55
  17       274    970        87     508     49
  18       209    897        87     400     33
  19       209    802        84     336     38
  20       160    678        75     316     42
  21       160    649        74     256     27
  22       123    592        57     259     29
  23        89    501        52     202     18
  24        95    462        59     179     15
  25        96    380        39     147     24
  26        61    355        31     140     22
  27        64    363        38     138     18
  28        53    312        24     113     23
  29        36    296        24     106     11
  30        42    262        22      76      7
  31        39    226        13      77     10
  32        28    217        18      72     19
  33        26    191        19      59      7
  34        25    186        13      62      8
  35        26    173        21      55      9
  36        20    163        13      38      9
  37        19    140        20      39      8
  38        16    140        10      36      6
  39        10    128        13      45      7
  40        16    111        11      28      3
  41        18     94         7      31     11
  42         8    103         5      27      4
  43        15    108         8      24      4
  44         7     77        17      24      5
  45         7     83         8      30      7
  46         7     77        11      21      5
  47        10     60         3      13      8
  48        10     60         6      19      1
  49         3     57         9      12      4
  50         5     58         6      18      1
  51         4     58         2       8      4
  52         9     48         5      11      2
  53         8     49         3      15      3
  54         3     45         4      12      1
  55         4     40         3       9      0
  56         3     33         5      10      0
  57         5     39         3       9      1
  58         3     41         1       4      2
  59         1     34         4       8      2
  60         3     37         3       8      1
  61         1     33         3       8      1
  62         0     31         1       5      2
  63         2     30         6       8      4
  64         2     13         2      11      0
  65         4     28         3       2      0
  66         3     23         1       2      1
  67         3     24         0       3      1
  68         2     27         2       5      1
  69         1     14         6       6      1
  70         3     20         6       5      0
  71         0     18         1       6      5
  72         0     10         2       1      0
  73         1     12         3       6      0
  74         1     22         3       2      0
  75         2     18         1       3      0
  76         1     11         2       2      1
  77         3     25         3       1      0
  78         1     15         1       7      1
  79         0     10         0       4      1
  80         2     11         1       4      3
  81         1     11         0       2      2
  82         0     15         0       2      0
  83         1     15         3       2      1
  84         1     12         1       2      1
  85         0      4         2       1      0
  86         3      6         1       1      1
  87         2      5         1       1      0
  88         0      8         1       3      1
  89         0      6         2       0      1
  90         0      8         0       2      0
  91         1      9         2       2      0
  92         1      7         1       1      0
  93         0      5         1       0      1
  94         0      9         4       1      0
  95         1      9         2       0      0
  96         1      4         2       3      1
  97         1      7         1       3      0
  98         0     10         0       1      0
  99         1     10         2       2      0
  100        1      5         1       1      0
  101        1      4         0       2      0
  102        1      7         3       0      1
  103        0      3         0       0      0
  104        0      3         0       1      0
  105        0      4         1       2      1
  106        0      7         1       0      0
  107        0      3         2       1      0
  108        0      2         1       1      0
  109        0      5         0       1      0
  110        0      3         1       1      0
  111        2      2         1       0      1
  112        0      1         1       1      0
  113        0      2         0       1      1
  114        0      5         1       0      0
  115        2      5         2       2      0
  116        1      6         0       2      0
  117        0      4         1       1      0
  118        0      3         0       1      0
  119        1      1         0       1      0
  120        0      2         0       0      1
  121        1      2         0       0      0
  122        0      1         0       0      1
  123        1      4         0       0      1
  124        0      0         1       0      0
  126        0      0         2       1      0
  127        1      0         0       0      0
  128        1      2         1       1      0
  129        0      1         0       1      0
  130        0      2         0       0      0
  131        1      1         0       0      0
  132        0      6         1       0      1
  133        0      4         0       1      0
  134        0      0         0       0      1
  135        0      2         0       0      0
  136        0      4         0       0      0
  137        0      3         0       1      0
  138        0      2         2       1      0
  139        1      3         0       2      0
  140        0      2         0       0      1
  141        0      3         1       2      1
  142        0      1         0       0      0
  144        0      3         0       1      0
  145        0      1         1       0      0
  146        0      0         0       4      0
  147        0      1         0       0      0
  148        0      0         0       1      6
  149        0      3         0       0      0
  150        0      1         0       0      0
  151        0      1         1       0      1
  152        0      2         0       0      0
  153        0      2         0       0      0
  154        0      4         0       0      1
  158        0      2         0       0      0
  162        0      1         0       0      0
  164        0      2         0       0      0
  167        0      1         1       0      0
  168        0      0         1       0      0
  169        2      1         1       0      0
  170        0      1         0       0      0
  172        0      1         0       0      0
  174        0      1         0       0      1
  176        0      0         0       1      0
  177        0      1         0       0      0
  178        0      1         1       0      0
  180        0      2         1       0      0
  181        0      0         0       1      0
  183        0      0         0       1      0
  184        0      0         0       0      1
  185        0      1         0       0      0
  186        0      1         0       0      0
  189        0      0         0       0      1
  190        0      0         0       1      0
  191        0      1         0       0      0
  197        0      0         0       0      1
  201        0      1         1       0      0
  202        0      1         0       0      0
  203        0      2         0       0      0
  204        0      1         0       0      0
  208        0      1         0       0      0
  213        0      0         0       1      0
  215        0      1         0       0      0
  218        0      1         0       0      0
  224        0      1         0       0      0
  227        0      1         0       0      0
  235        0      1         0       0      0
  239        0      1         0       0      0
  245        0      2         0       0      0
  246        0      0         1       0      0
  255        0      1         0       0      0
  258        0      1         0       0      0
  259        0      1         0       0      0
  260        0      1         0       0      0
  263        0      1         0       0      0
  267        0      0         0       1      0
  272        0      1         0       0      0
  273        0      0         0       0      2
  282        0      1         0       0      0
  290        0      0         1       0      0
  292        0      1         0       0      0
  343        0      0         0       1      0
  356        0      1         0       0      0
  562        0      1         0       0      0
  13185      0      0         0       0      1</code></pre>
</div>
</div>
<p>Examining authors’ gender assignment by number of articles written, we find that the percentage of authors with unassigned genders increases slightly with the number of articles written, suggesting that prolific authors are more likely to have names unrecognized by gender algorithms and highlighting the challenges associated with gender assignment in diverse cultural contexts. For instance, among authors, 501 694 have written only 1 article, 44.3% (36 326 + 21 058 + 165 074/501 694) have an “undetermined”, “unknown” or complete unassigned gender, while among the authors that have written that have written 273, 292 or 343 articles, 100% have a complete unassigned gender.</p>
<p>Commentaire: l’interprétation n’est pas forcément évidente. Ne faudrait-il pas rajouter à ce tableau deux colonnes : une qui compte le nombre d’auteurs qui ont écrit x articles et une qui compte la proportion de «undetermined», «unknown» et «NA» sur le nombre d’auteurs qui ont écrit x articles ? Cela permettrait une analyse beaucoup plus simple car à vue d’oeil ce n’est pas sur que l’interprétation soit correcte.</p>
</section>
</section>
<section id="analysis-of-gender-assignment-at-article-level" class="level4">
<h4 class="anchored" data-anchor-id="analysis-of-gender-assignment-at-article-level">Analysis of gender assignment at article level</h4>
<p>It is also possible to perform the analysis using the variable that gives, by article, the percentage of authors whose gender is correctly identified among the total number of authors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  Nb_articles  NoGender AllGender Gender_Larger0.5 Gender_Larger0.9
1     1136055 0.2991554 0.4840074        0.6524684        0.4844765
  Gender_Larger0.25 Mean_IdentifiedGender Median_identifiedGender
1         0.6949382             0.5986791                    0.75</code></pre>
</div>
</div>
<p>Gender analysis at article level shows that around 30% of articles do not allow gender to be assigned to a single author. This indicates a significant difficulty in identifying the gender of a significant proportion of articles. On the other hand, for over 48% of articles, the gender of all authors is correctly identified. This majority proportion demonstrates a certain efficiency in gender assignment. For 65% of articles, it is possible to assign the gender to at least half of the authors. This shows that most articles have at least partial gender identification among their authors. Around half the articles allow gender to be assigned to 90% of the authors. This high proportion reflects almost complete gender identification for a significant proportion of articles, illustrating the effectiveness of the algorithms or methods used for gender assignment. Finally, for around 70% of the articles, it is possible to assign the gender to 25% of the authors. This figure indicates that, even in the most difficult cases, it is still possible to determine the gender of a proportion of authors, which may be sufficient for certain statistical analyses.</p>
</section>
</section>
<section id="descriptive-statistics-and-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics-and-data-analysis">Descriptive statistics and data analysis</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>OneGender_by_Articles <span class="ot">&lt;-</span> Corpus.CleanedNames<span class="fl">.2</span> <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Nb_articles =</span> <span class="fu">length</span>(ratio_identified_gender), <span class="co"># Nb total d'article</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">NoGender =</span> <span class="fu">length</span>(ratio_identified_gender[<span class="fu">is.na</span>(ratio_identified_gender) <span class="sc">|</span> ratio_identified_gender <span class="sc">==</span> <span class="dv">0</span>]) <span class="sc">/</span> Nb_articles)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>OneGender_by_Articles</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Nb_articles  NoGender
1     1136055 0.2991554</code></pre>
</div>
</div>
<p>First, we can remind that the absolute number of articles with at least 1 author identified in terms of gender is 1 136 055. Thus, there is at least 70% of our articles whose gender has been assigned to at least one author.</p>
<section id="proportion-of-male-and-female-authors-at-an-aggregate-level" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-male-and-female-authors-at-an-aggregate-level">Proportion of male and female authors at an aggregate level</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        Statistic Proportion_Female_All Proportion_Female_Id Sum_Gender_Female
Min.          Min          0.0000000000            0.0000000         0.0000000
1st Qu.   1st Qu.          0.0004333333            0.0005000         0.0009000
Median     Median          0.0047000000            0.0051000         0.0083000
Mean         Mean          0.2165370610            0.2561972         0.5070374
3rd Qu.   3rd Qu.          0.3985550000            0.5000000         1.0000000
Max.          Max          1.0000000000            1.0000000        11.9845000
        Sum_Gender_Male Proportion_Male_All Proportion_Male_Id
Min.           0.000000           0.0000000          0.0000000
1st Qu.        0.995100           0.3342333          0.5000000
Median         1.000000           0.6654333          0.9949000
Mean           1.326995           0.6376968          0.7438148
3rd Qu.        1.993400           0.9963000          0.9995000
Max.          14.987500           1.0000000          1.4621500</code></pre>
</div>
</div>
<p>This analysis presents descriptive statistics of gender proportions among authors of academic articles. Variables analyzed include the proportion of female and male authors, both among all authors and among those whose gender was successfully assigned, as well as the sum of male and female gender probabilities for each article.</p>
<p>The results indicate a wide variation in gender proportions among authors. The proportion of female authors among all authors ranges from 0 to 1, with an average of 0.2165, meaning that on average, around 21.65% of authors are female. The proportion of female authors among gender-assigned authors has a slightly higher average of 25.62%, suggesting that women may be better identified among authors. In comparison, the proportion of male authors among all authors is also highly variable, with an average of 63.77%. The proportion of male authors among gender-assigned authors is 74.38% on average, which is higher than for women.</p>
<p>The results therefore reveal a notable under-representation of women among authors of academic articles in terms of proportion. These results highlight the need for continued efforts to encourage and support women’s participation in the academic field.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graphs below illustrate the distributions of male and female gender proportions among authors whose gender has been assigned. The analysis focuses on two separate histograms, one representing the proportion of male authors and the other the proportion of female authors.</p>
<p>The histogram of the proportion of male authors shows a broadly spread distribution, with a high frequency of values close to 1. This indicates that a large number of articles have a majority proportion of male authors. The distribution also shows a marked asymmetry to the right, reflecting the fact that few articles have a low proportion of male authors.</p>
<p>The histogram of the proportion of female authors reveals a different distribution. Most values lie between 0 and 0.5, with a notable peak at the lower values. This distribution shows that there are relatively few articles with a high proportion of female authors, and many articles have lower proportions of women. In contrast to the distribution for men, this distribution is asymmetrical towards the left, indicating that the predominance of women among authors is less common.</p>
<p>A comparison of these two distributions reveals a significant under-representation of women among authors of academic articles. While the proportion of men tends to be high in many articles, that of women remains low in the majority of cases. These observations are consistent with previous statistical findings, underlining the need for ongoing efforts to balance gender representation in academia. The disparity observed in the distributions calls for reflection on the factors contributing to this inequality, and the development of strategies to promote greater inclusion of women in scientific research.</p>
</section>
<section id="proportion-of-female-and-male-authors-according-to-different-type-of-collaboration" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-female-and-male-authors-according-to-different-type-of-collaboration">Proportion of female and male authors according to different type of collaboration</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  category_gender Mean_Proportion_Female_Id Median_Proportio…¹ Mean_Pr…² Media…³
  &lt;chr&gt;                               &lt;dbl&gt;              &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 F                                 0.995               0.999    0.00535  0.0007
2 FF                                0.996               0.998    0.00433  0.0017
3 M                                 0.00486             0.0019   0.995    0.998 
4 MF                                0.464               0.500    0.536    0.500 
5 MM                                0.00457             0.0026   0.995    0.997 
6 &lt;NA&gt;                            NaN                  NA      NaN       NA     
# … with abbreviated variable names ¹​Median_Proportion_Female_Id,
#   ²​Mean_Proportion_Male_Id, ³​Median_Proportion_Male_Id</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This section presents an analysis of collaboration categories within academic research according to author gender. Descriptive statistics include the mean and median proportion of female and male authors assigned per category.</p>
<p>Let’s focus on the “MF” category, which represents articles written by authors of both genders. The average proportion of female authors in this category is around 46.36%, while the average proportion of male authors is slightly higher, at around 53.64%. This near-equality of proportions indicates a remarkable gender parity in mixed collaborations. Unlike the “F” and “FF” categories, where women are almost exclusively the sole authors, or the “M” and “MM” categories, where men strongly dominate, the “MF” category shows a more balanced distribution.</p>
<p>This is a significant result, as it underlines the importance of mixed collaborations in achieving a more balanced gender representation in academic research. The almost equal presence of men and women in mixed collaborations may reflect a more inclusive and diversified work dynamic. This parity in proportions could foster a research environment where the ideas and perspectives of both genders are better represented and integrated. Promoting this type of collaboration could be an effective way of reducing gender inequalities in academia. Policies and initiatives to encourage mixed-gender collaborations could thus play a crucial role in advancing gender equity in science and research.</p>
</section>
<section id="overall-temporal-evolution" class="level3">
<h3 class="anchored" data-anchor-id="overall-temporal-evolution">Overall Temporal evolution</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 75 × 3
      PY Mean_Proportion_Female_Id Mean_Proportion_Male_Id
   &lt;dbl&gt;                     &lt;dbl&gt;                   &lt;dbl&gt;
 1  1950                    0.0614                   0.939
 2  1951                    0.0697                   0.930
 3  1952                    0.0523                   0.948
 4  1953                    0.0642                   0.936
 5  1954                    0.0454                   0.955
 6  1955                    0.0656                   0.934
 7  1956                    0.100                    0.900
 8  1957                    0.100                    0.900
 9  1958                    0.128                    0.872
10  1959                    0.0971                   0.903
# … with 65 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This section presents the evolution of the average proportion of female and male authors in academic publications, from 1950 to 2023. It reveals significant trends over several decades, highlighting gender dynamics in academic research.</p>
<p>From 1950 to 1970, the average proportion of female authors remained remarkably low, hovering around 0.06. During this period, male authors largely dominated publications, with proportions approaching 0.94. This disparity underlines the predominance of men in the academic field at the time.</p>
<p>Between 1970 and 1990, a slight increase in the proportion of female authors was observed, rising from around 0.12 to 0.15. This period marks the beginning of a gradual change, although men continue to represent a substantial majority.The increase remains modest, but indicates a trend towards gender diversification among academic authors.</p>
<p>From the 1990s onwards, the average proportion of female authors began to rise more significantly. By 1995, this proportion had risen to around 0.18, indicating greater inclusion of women in academic publications. This trend has continued steadily, with the proportion reaching around 0.30 in 2017. At the same time, the average proportion of male authors is gradually decreasing, but remains dominant.</p>
<p>Since 2017, the average proportion of female authors has exceeded 0.30, reaching 0.32 in 2020. This growth indicates increasing gender parity, although men continue to constitute a relative majority with an average proportion around 0.68. Recent years have seen a stabilization of these proportions, with slight fluctuations.</p>
<p>In conclusion, this section illustrates a positive trend towards greater inclusion of women in academic research over the decades. Although men are still in the majority, the continuing growth in the proportion of female authors bears witness to a gradual shift towards more balanced gender representation in scientific publications.</p>
</section>
<section id="temporal-evolution-according-to-categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="temporal-evolution-according-to-categorical-variables">Temporal evolution according to categorical variables</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 435 × 4
      PY category_gender Mean_Proportion_Female_Id Mean_Proportion_Male_Id
   &lt;dbl&gt; &lt;chr&gt;                               &lt;dbl&gt;                   &lt;dbl&gt;
 1  1950 F                                 0.997                   0.00276
 2  1950 M                                 0.00617                 0.994  
 3  1950 MF                                0.366                   0.634  
 4  1950 MM                                0.00694                 0.993  
 5  1950 &lt;NA&gt;                            NaN                     NaN      
 6  1951 F                                 0.992                   0.00819
 7  1951 M                                 0.00611                 0.994  
 8  1951 MF                                0.479                   0.521  
 9  1951 MM                                0.00610                 0.994  
10  1951 &lt;NA&gt;                            NaN                     NaN      
# … with 425 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 152 rows containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This section provides an analysis of the evolution of average author proportions by gender from 1950 to 2023, and highlights significant dynamics in academic collaborations.</p>
<p>Analysis of gender proportions in mixed collaborations (MF) from 1950 to 2023 reveals that in 1950, female authors represented an average of 37% of mixed teams, compared with 63% for male authors. This male dominance persisted until the 1960s. In the 1970s, the average proportion of female authors reached 48%, marking progress towards greater integration of women. From the 2000s onwards, the proportion of women authors continued to rise, although at just under 46%, reflecting a positive trend towards greater parity.</p>
<p>The data thus show a gradual integration of women into mixed collaborations, indicating steady progress towards gender parity in academic research, despite the persistence of a slight male majority.</p>
</section>
<section id="temporal-evolution-according-to-categorical-variables-by-number-of-articles" class="level3">
<h3 class="anchored" data-anchor-id="temporal-evolution-according-to-categorical-variables-by-number-of-articles">Temporal evolution according to categorical variables, by number of articles</h3>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'PY'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 435 × 3
# Groups:   PY [75]
      PY category_gender nb_articles
   &lt;dbl&gt; &lt;chr&gt;                 &lt;int&gt;
 1  1950 F                        27
 2  1950 M                       491
 3  1950 MF                       12
 4  1950 MM                       33
 5  1950 &lt;NA&gt;                    368
 6  1951 F                        35
 7  1951 M                       525
 8  1951 MF                        6
 9  1951 MM                       21
10  1951 &lt;NA&gt;                    365
# … with 425 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6 rows containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Analysis of data on the number of articles by gender category from 1950 to 2021 reveals some interesting, albeit nuanced, trends. In 1950, the “M” category (exclusively male) dominated, with 491 articles. The “F” (all-female) and “MF” (mixed) categories accounted for 27 and 12 items respectively.</p>
<p>In subsequent years, trends changed significantly. For example, in 1960, although the “M” category remained dominant with 381 items, the “F” and “MM” categories showed an increase compared to 1950. However, missing data also began to appear more pronounced.</p>
<p>The 1970s mark a notable change, with a significant increase in the number of articles in all categories, including a notable rise in missing data. The “F” category began to show gradual growth, reaching 130 articles in 1970.</p>
<p>From the 2000s onwards, all categories see a marked increase in the number of articles, reflecting a global expansion of academic research. The “MF” (mixed collaboration) category grows particularly rapidly, peaking in 2021 with 16,267 articles, but missing data also increases drastically.</p>
<p>In conclusion, these data illustrate not only the quantitative expansion of scientific research over the decades, but also changes in the gendered composition of research teams, with a significant increase in mixed collaboration. However, it is crucial to take into account the impact of missing data, which can influence the interpretation of these upward trends.</p>
</section>
<section id="analysis-of-articles-on-climate-change-at-an-aggregate-level" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-articles-on-climate-change-at-an-aggregate-level">Analysis of articles on climate change at an aggregate level</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
     CC Mean_Proportion_Female_Id Median_Proportion_Female_Id Mean_Pro…¹ Media…²
  &lt;dbl&gt;                     &lt;dbl&gt;                       &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
1     0                     0.255                     0.00505      0.745   0.995
2     1                     0.283                     0.016        0.717   0.984
# … with abbreviated variable names ¹​Mean_Proportion_Male_Id,
#   ²​Median_Proportion_Male_Id</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Analysis of the data on articles relating to climate change, grouped according to the binary variable “CC” (climate change), reveals notable differences in the gendered composition of authors.</p>
<p>Looking at the descriptive statistics, we see that in the category where the theme of climate change is central (“CC = 1”), the average proportion of female authors is slightly higher than in the “CC = 0” category. In detail, the average proportion of female authors is 28.29% in the “CC = 1” category, compared with 25.53% in the “CC = 0” category. On the other hand, the “CC = 0” category shows a greater predominance of male authors, with an average of 74.47%, compared to the “CC = 1” category where the average is 71.71%.</p>
<p>These results highlight a distinct gendered distribution in climate change-related publications, with a predominance of male authors in both categories but more female authors in articles that focus on climate change, thus indicating varied dynamics in gender participation depending on the specific research theme.</p>
</section>
<section id="climate-change-category-gender-and-number-of-articles" class="level3">
<h3 class="anchored" data-anchor-id="climate-change-category-gender-and-number-of-articles">Climate change, category gender and number of articles</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
      CC category_gender nb_articles
   &lt;dbl&gt; &lt;chr&gt;                 &lt;int&gt;
 1     0 F                     86249
 2     0 FF                    30631
 3     0 M                    296893
 4     0 MF                   167934
 5     0 MM                   188404
 6     0 &lt;NA&gt;                 334413
 7     1 F                      2503
 8     1 FF                     1131
 9     1 M                      6994
10     1 MF                     8310
11     1 MM                     7149
12     1 &lt;NA&gt;                   5444</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Analysis of the data on the number of articles relating to climate change, represented by the binary variable “CC” (climate change) and the gender category, reveals some interesting trends in the distribution of publications.</p>
<p>Looking at the descriptive statistics, we observe a marked disparity in the number of articles published according to gender category and type of scientific research. In the “CC = 0” category (not focused on climate change), the distribution of articles by gender is significantly different from that observed in the “CC = 1” category (focused on climate change).</p>
<p>For the “CC = 0” category, which does not deal specifically with climate change, the data show a significant predominance of articles attributed to the masculine (296,893 articles) and feminine (86,249 articles) genders, followed by mixed gender combinations (167,934 articles for MF, 188,404 articles for MM). In contrast, the “CC = 1” category shows lower overall articles numbers, with a similar trend of male predominance, but with a slightly higher proportion of items attributed to mixed gender combinations (8,310 articles for MF, 7,149 articles for MM). Analysis of the number of articles by genre category therefore reveals that, despite the lower overall quantity of articles in the “CC = 1” category, mixed-genre combinations account for a significant share compared with the other categories, underlining an increased diversity in scientific collaborations focused on climate change.</p>
</section>
<section id="temporal-evolution-of-the-proportion-of-female-authors-by-cc" class="level3">
<h3 class="anchored" data-anchor-id="temporal-evolution-of-the-proportion-of-female-authors-by-cc">Temporal evolution of the proportion of female authors by CC</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 124 × 3
      PY    CC Mean_Proportion_Female_Id
   &lt;dbl&gt; &lt;dbl&gt;                     &lt;dbl&gt;
 1  1950     0                    0.0614
 2  1951     0                    0.0697
 3  1952     0                    0.0523
 4  1953     0                    0.0642
 5  1954     0                    0.0454
 6  1955     0                    0.0656
 7  1956     0                    0.100 
 8  1957     0                    0.100 
 9  1958     0                    0.128 
10  1959     0                    0.0971
# … with 114 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6 rows containing missing values (`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This section provides descriptive statistics and an analysis of the time trend in the proportion of authors identified as “women”, for articles dealing with climate change (“CC” = 1) compared with articles not dealing with climate change (CC = 0). Analysis of the results shows an upward trend in the proportion of women in both categories. For example, in 1983, the proportion of women authors was 13.5%, whereas it was 30.1% in 2017. For articles on climate change, the proportion was 0.4% in 1989, compared with 23% in 2023. The increase in the proportion of women is therefore more marked in climate economics research than in other types of economic research.</p>
<p>###.Focus on Top5 and Top30 journals and on climte change</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'TopFive'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
# Groups:   TopFive [2]
  TopFive    CC Mean_Proportion_Female_Id Median_Proportion_Fe…¹ Media…² Mean_…³
    &lt;dbl&gt; &lt;dbl&gt;                     &lt;dbl&gt;                  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1       0     0                     0.257                0.0051    0.995   0.743
2       0     1                     0.283                0.0163    0.984   0.717
3       1     0                     0.143                0.00205   0.998   0.857
4       1     1                     0.124                0.00375   0.996   0.876
# … with abbreviated variable names ¹​Median_Proportion_Female_Id,
#   ²​Median_Proportion_Male_Id, ³​Mean_Proportion_Male_Id</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Top30'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
# Groups:   Top30 [2]
  Top30    CC Mean_Proportion_Female_Id Median_Proportion_Fema…¹ Media…² Mean_…³
  &lt;dbl&gt; &lt;dbl&gt;                     &lt;dbl&gt;                    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     0     0                     0.260                  0.00525   0.995   0.740
2     0     1                     0.285                  0.0171    0.983   0.715
3     1     0                     0.172                  0.0034    0.997   0.828
4     1     1                     0.138                  0.0032    0.997   0.862
# … with abbreviated variable names ¹​Median_Proportion_Female_Id,
#   ²​Median_Proportion_Male_Id, ³​Mean_Proportion_Male_Id</code></pre>
</div>
</div>
<p>This section provides descriptive statistics on the proportion of women and men by journal type and research theme. For articles not related to climate change (CC = 0), the average proportion of female authors is higher in Top 30 journals (26.05%) than in Top 5 journals (14.26%). This suggests a more significant representation of female authors in the lower-quality newspapers for this type of article.</p>
<p>On the other hand, for articles on climate change (CC = 1), although the trend is similar, with a higher average proportion of female authors in Top 30 (13.80%) compared to Top 5 (12.41%), the gap is less marked than for articles not related to climate change.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 339857 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 339857 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="QuantifCCEcon_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>In conclusion, this study provides a comprehensive quantitative analysis of gender disparities within the field of climate economics, focusing on authorship dynamics across different levels of journal prestige and types of collaborations. Our findings underscore several key observations. While strides have been made towards gender equality in academic authorship, persistent disparities necessitate ongoing efforts to promote diversity and inclusivity in research collaborations and methodologies. Addressing these challenges is essential for advancing a more equitable and representative academic landscape in climate economics and beyond.</p>
<p>Firstly, our data analysis reveals persistent gender imbalances in academic publishing, with a notable underrepresentation of female authors across all categories. While the average proportion of female authors is slightly higher in climate change-related articles compared to those not focused on climate change, both areas exhibit a predominantly male authorship landscape. Secondly, our study highlights the impact of collaboration types on gender representation. Mixed-gender collaborations (MF) demonstrate a more balanced distribution of authors, suggesting that fostering such collaborations could contribute to greater gender equity in academic research. Moreover, our analysis of temporal trends reveals a gradual increase in the proportion of female authors over the decades, indicating positive albeit slow progress towards gender parity in academic publishing. This trend is more pronounced in climate economics compared to broader economic research, reflecting evolving dynamics within specific research domains. However, our study also identifies significant challenges in gender assignment methodologies, particularly in handling non-Western names, which remain a crucial limitation affecting the accuracy and inclusivity of gender analyses in academic research.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>